### ISSUE TITLE
Order of services/links

### ISSUE THREAD

**Issue by pduchnovsky** [santimar/traefik-home#51]
First of all, I love this !
Status light is especially very nice and helpful.

However I got a question/suggestion, Is there any way on how to order them ?
They are sorted by container creation date, which isn't optimal.
I'd love to have possibility for alphabet ordering or custom ordering as well.

**Comment by santimar** [comment]
Hi @pduchnovsky 
right now sorting is not implemented and as you saw.

Sorting by name should be easy to obtain, while a custom ordering may be more tricky to get.

If you want to submit a PR, feel free.
To implement an alphabetic sort should be sufficient to do something like:
```
{{ $sort_order := or (index $home_container.Labels "traefik-home.sort-by") "default" }}
...
    <div class="container my-auto pb-4">
        {{/* Display only containers explicitly enabled */}}
        {{ $containers := whereLabelValueMatches $ "traefik.enable" "true" }}
        {{ if eq $sort_order "name" }}
          {{ $containers = sortObjectsByKeysAsc $containers "Name" }}
        {{ end }}
        <div class="row align-content-center justify-content-evenly">  
```

At the moment I'm a bit busy, but I will try to implement it whenever I can.

**Comment by pduchnovsky** [comment]
I managed to get it work with the example above, however, could you please advice how to make them sorted by Alias as well ? :)

**Comment by santimar** [comment]
Thanks for the PR, looks great!
Few days and I will give it a try.

What do you mean by alias?
You should be able to sort by every field listed in the `RuntimeContainer` [here](https://github.com/nginx-proxy/docker-gen#emit-structure), just replace `Name` with `Hostname`, `ID`, `Gateway`, etc (probably should work even with nested fields like `State.Running`)
